import type { SQL } from "bun";
import { callGemini, TEMPERATURE } from "../gemini";
import { recordTokenUsage } from "../../db/aiQueries";

/**
 * Per-developer weekly coaching card. Generated by the coachingCards job.
 *
 * Privacy contract:
 * - Operates on a single developer's own session data.
 * - Output is rendered ONLY to the user linked to that developer (server-side check).
 * - Prompt forbids comparisons, rankings, and references to other developers.
 */

export interface CoachingRecommendation {
  type: "strength" | "improvement" | "action";
  title: string;
  body: string;
  impact: "high" | "medium" | "low";
  evidence_session_ids: string[];
}

export interface CoachingCardResult {
  recommendations: CoachingRecommendation[];
  inputTokens: number;
  outputTokens: number;
}

interface DevWeekData {
  session_count: number;
  completed_sessions: number;
  avg_duration_min: number;
  total_prompts: number;
  top_tools: { tool: string; uses: number; failures: number }[];
  intent_breakdown: { intent: string; count: number }[];
  friction_events: { type: string; severity: string; title: string; session_id: string }[];
  recent_session_ids: string[];
}

async function gatherDevData(
  sql: SQL,
  developerId: string,
): Promise<DevWeekData> {
  const [overview] = (await sql`
    SELECT
      COUNT(*)::INT as session_count,
      SUM(CASE WHEN s.status = 'ended' THEN 1 ELSE 0 END)::INT as completed_sessions,
      ROUND(
        AVG(EXTRACT(EPOCH FROM (COALESCE(s.ended_at, NOW()) - s.started_at)) / 60)::NUMERIC, 1
      )::FLOAT as avg_duration_min
    FROM sessions s
    WHERE s.developer_id = ${developerId}
      AND s.started_at >= NOW() - INTERVAL '7 days'`) as any[];

  const [prompts] = (await sql`
    SELECT COUNT(*)::INT as total_prompts
    FROM events e JOIN sessions s ON e.session_id = s.id
    WHERE s.developer_id = ${developerId}
      AND e.event_type = 'prompt.submit'
      AND e.created_at >= NOW() - INTERVAL '7 days'`) as any[];

  const tools = (await sql`
    SELECT
      e.payload->>'toolName' as tool,
      COUNT(*)::INT as uses,
      SUM(CASE WHEN e.event_type = 'tool.fail' THEN 1 ELSE 0 END)::INT as failures
    FROM events e JOIN sessions s ON e.session_id = s.id
    WHERE s.developer_id = ${developerId}
      AND e.event_type IN ('tool.complete', 'tool.fail')
      AND e.payload->>'toolName' IS NOT NULL
      AND e.created_at >= NOW() - INTERVAL '7 days'
    GROUP BY tool
    ORDER BY uses DESC
    LIMIT 8`) as any[];

  const intents = (await sql`
    SELECT
      COALESCE(s.session_intent, 'unclassified') as intent,
      COUNT(*)::INT as count
    FROM sessions s
    WHERE s.developer_id = ${developerId}
      AND s.started_at >= NOW() - INTERVAL '7 days'
    GROUP BY intent
    ORDER BY count DESC`) as any[];

  const friction = (await sql`
    SELECT fa.rule_type as type, fa.severity, fa.title, fa.session_id
    FROM friction_alerts fa
    WHERE fa.developer_id = ${developerId}
      AND fa.triggered_at >= NOW() - INTERVAL '7 days'
    ORDER BY fa.triggered_at DESC
    LIMIT 20`) as any[];

  const sessions = (await sql`
    SELECT s.id
    FROM sessions s
    WHERE s.developer_id = ${developerId}
      AND s.started_at >= NOW() - INTERVAL '7 days'
    ORDER BY s.started_at DESC
    LIMIT 30`) as any[];

  return {
    session_count: overview?.session_count ?? 0,
    completed_sessions: overview?.completed_sessions ?? 0,
    avg_duration_min: overview?.avg_duration_min ?? 0,
    total_prompts: prompts?.total_prompts ?? 0,
    top_tools: tools.map((t: any) => ({
      tool: t.tool,
      uses: t.uses,
      failures: t.failures,
    })),
    intent_breakdown: intents.map((i: any) => ({
      intent: i.intent,
      count: i.count,
    })),
    friction_events: friction.map((f: any) => ({
      type: f.type,
      severity: f.severity,
      title: f.title,
      session_id: f.session_id,
    })),
    recent_session_ids: sessions.map((s: any) => s.id),
  };
}

const COACHING_PROMPT = `You write a personal coaching card for a single developer about their own Claude Code usage over the past week.

TONE & SCOPE RULES — non-negotiable:
- Address the developer in second person ("You", "your sessions").
- NEVER compare to peers, teams, averages, or other developers.
- NEVER use words like "more than", "less than", "below", "above", "ranking", "top", "bottom" relative to other people.
- NEVER reference other developers, even anonymously.
- Base every recommendation on this developer's own data only.
- Each recommendation must include the specific session IDs it draws evidence from (from the data given).
- If data is sparse (under ~5 sessions or no friction events), output 1 short observation, not invented advice.

OUTPUT — strict JSON, no markdown, no code fences:
{
  "recommendations": [
    {
      "type": "strength" | "improvement" | "action",
      "title": "short, concrete title (under 60 chars)",
      "body": "1-3 sentences. Specific. Reference what you saw in the data.",
      "impact": "high" | "medium" | "low",
      "evidence_session_ids": ["session-id-1", ...]
    }
  ]
}

Generate 1 to 3 recommendations. Quality over quantity. Mix types — at least one "action" if there is any actionable signal.

Examples of GOOD coaching:
- "Try /investigate for repeated test flakes" — when friction shows repeated failures
- "Your Bash retries on \`bun test\` cluster mid-session — pause and inspect the failure once before re-running"
- "Strength: focused sessions averaging 12 minutes — you're decomposing well"

Examples of BAD coaching (do NOT produce):
- "You wrote less code than the team average" (comparison)
- "Improve your prompts" (vague)
- "Use Claude better" (not actionable)

Developer data:
`;

export async function generateCoachingCard(
  sql: SQL,
  developerId: string,
): Promise<CoachingCardResult> {
  const data = await gatherDevData(sql, developerId);

  // Skip if not enough signal — caller should check this
  if (data.session_count < 3) {
    return { recommendations: [], inputTokens: 0, outputTokens: 0 };
  }

  const prompt = COACHING_PROMPT + JSON.stringify(data, null, 2).slice(0, 25_000);

  const response = await callGemini(
    [{ role: "user", parts: [{ text: prompt }] }],
    undefined,
    { temperature: TEMPERATURE.insight },
  );

  const cleaned = response.text
    .replace(/```json?\n?/g, "")
    .replace(/```/g, "")
    .trim();

  let recommendations: CoachingRecommendation[] = [];
  try {
    const parsed = JSON.parse(cleaned);
    if (Array.isArray(parsed?.recommendations)) {
      recommendations = parsed.recommendations
        .filter(
          (r: any) =>
            r &&
            typeof r.title === "string" &&
            typeof r.body === "string" &&
            ["strength", "improvement", "action"].includes(r.type) &&
            ["high", "medium", "low"].includes(r.impact),
        )
        .slice(0, 3)
        .map((r: any) => ({
          type: r.type,
          title: String(r.title).slice(0, 120),
          body: String(r.body).slice(0, 600),
          impact: r.impact,
          evidence_session_ids: Array.isArray(r.evidence_session_ids)
            ? r.evidence_session_ids
                .filter((s: any) => typeof s === "string")
                .filter((s: string) => data.recent_session_ids.includes(s))
                .slice(0, 5)
            : [],
        }));
    }
  } catch (err) {
    console.error(
      "[coaching-card] Failed to parse Gemini response:",
      response.text.slice(0, 200),
      err,
    );
  }

  await recordTokenUsage(
    sql,
    "coaching-card",
    "gemini-flash",
    response.inputTokens,
    response.outputTokens,
  );

  return {
    recommendations,
    inputTokens: response.inputTokens,
    outputTokens: response.outputTokens,
  };
}
